# This file was generated by GoReleaser. DO NOT EDIT.
cask "lodev" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "e42009af787bc15dc2eb38b5d1e2e225ac10ad85d3a3815361c59add402d315f"
      url "https://github.com/namnh198/lodev/releases/download/v#{version}/lodev_macos-amd64.v#{version}.tar.gz",
        verified: "github.com/namnh198/lodev/",
        using: :homebrew_curl,
        cookies: {
          "license" => "accept-backup",
        }
    end
    on_arm do
      sha256 "c5327110cb0be00e7b72d9ffb8d0ec0faab9c4828770a8fabbf758f05cda5d18"
      url "https://github.com/namnh198/lodev/releases/download/v#{version}/lodev_macos-arm64.v#{version}.tar.gz",
        verified: "github.com/namnh198/lodev/",
        using: :homebrew_curl,
        cookies: {
          "license" => "accept-backup",
        }
    end
  end

  on_linux do
    on_intel do
      sha256 "0a60540b36853afb0125b53096c6c2daae3e24a5f22716f065f839dcc4935bbb"
      url "https://github.com/namnh198/lodev/releases/download/v#{version}/lodev_linux-amd64.v#{version}.tar.gz",
        verified: "github.com/namnh198/lodev/",
        using: :homebrew_curl,
        cookies: {
          "license" => "accept-backup",
        }
    end
    on_arm do
      sha256 "e3abf9062f4701de3cdb66392ad9c7e0f806752ba7d27b3232238e45da73c9c9"
      url "https://github.com/namnh198/lodev/releases/download/v#{version}/lodev_linux-arm64.v#{version}.tar.gz",
        verified: "github.com/namnh198/lodev/",
        using: :homebrew_curl,
        cookies: {
          "license" => "accept-backup",
        }
    end
  end

  name "lodev"
  desc "LODEV - Local Development Environment for Docker"
  homepage "https://github.com/namnh198/lodev"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "mkcert",
    ]

  binary "lodev"
  bash_completion "completions/lodev_bash_completions.bash"
  fish_completion "completions/lodev_fish_completions.fish"
  zsh_completion "completions/lodev_zsh_completions.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/lodev"]
    end
  end

  # No zap stanza required

end
