# This file was generated by GoReleaser. DO NOT EDIT.
cask "lodev" do
  version "0.1.3"

  on_macos do
    on_intel do
      sha256 "d46cc9c22ec9d9408b576836402f3a13e396b40a24c9ffc93d5314cd9c0f3be5"
      url "https://github.com/namnh198/lodev/releases/download/v#{version}/lodev_macos-amd64.v#{version}.tar.gz",
        verified: "github.com/namnh198/lodev/",
        using: :homebrew_curl,
        cookies: {
          "license" => "accept-backup",
        }
    end
    on_arm do
      sha256 "3f9e7e546307e5f068d787170a721eb4f9d70e5144ba1e20ac857a59dd912089"
      url "https://github.com/namnh198/lodev/releases/download/v#{version}/lodev_macos-arm64.v#{version}.tar.gz",
        verified: "github.com/namnh198/lodev/",
        using: :homebrew_curl,
        cookies: {
          "license" => "accept-backup",
        }
    end
  end

  on_linux do
    on_intel do
      sha256 "59be044adb551959756a2d33e960cbeb7113b6fddfa6663c8e863166d5c71691"
      url "https://github.com/namnh198/lodev/releases/download/v#{version}/lodev_linux-amd64.v#{version}.tar.gz",
        verified: "github.com/namnh198/lodev/",
        using: :homebrew_curl,
        cookies: {
          "license" => "accept-backup",
        }
    end
    on_arm do
      sha256 "1af5b4845c0cd553b7f195d632fdb71834cff2bddde3c4cc4235176848a2f75f"
      url "https://github.com/namnh198/lodev/releases/download/v#{version}/lodev_linux-arm64.v#{version}.tar.gz",
        verified: "github.com/namnh198/lodev/",
        using: :homebrew_curl,
        cookies: {
          "license" => "accept-backup",
        }
    end
  end

  name "lodev"
  desc "LODEV - Local Development Environment for Docker"
  homepage "https://github.com/namnh198/lodev"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "mkcert",
    ]

  binary "lodev"
  bash_completion "completions/lodev_bash_completions.bash"
  fish_completion "completions/lodev_fish_completions.fish"
  zsh_completion "completions/lodev_zsh_completions.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/lodev"]
    end
  end

  # No zap stanza required

end
