# This file was generated by GoReleaser. DO NOT EDIT.
cask "lodev" do
  version "0.1.2"

  on_macos do
    on_intel do
      sha256 "1356a1648cd7b9e55acf23b4f478641a2d9228b18524d0174c3969f3d64bbb85"
      url "https://github.com/namnh198/lodev/releases/download/v#{version}/lodev_macos-amd64.v#{version}.tar.gz",
        verified: "github.com/namnh198/lodev/",
        using: :homebrew_curl,
        cookies: {
          "license" => "accept-backup",
        }
    end
    on_arm do
      sha256 "afb904a641352c0fd9f779a6a9a22f97bc0667521f79cf5c183d46fac1ef82ed"
      url "https://github.com/namnh198/lodev/releases/download/v#{version}/lodev_macos-arm64.v#{version}.tar.gz",
        verified: "github.com/namnh198/lodev/",
        using: :homebrew_curl,
        cookies: {
          "license" => "accept-backup",
        }
    end
  end

  on_linux do
    on_intel do
      sha256 "7a9adab7ca92dc3b68eff687d79ad03abb4cc80c272925eab88170abac3dbbfd"
      url "https://github.com/namnh198/lodev/releases/download/v#{version}/lodev_linux-amd64.v#{version}.tar.gz",
        verified: "github.com/namnh198/lodev/",
        using: :homebrew_curl,
        cookies: {
          "license" => "accept-backup",
        }
    end
    on_arm do
      sha256 "6c3eac7a587a15118102228148b2334b5b30856ac0279dae26460a855bfb09b9"
      url "https://github.com/namnh198/lodev/releases/download/v#{version}/lodev_linux-arm64.v#{version}.tar.gz",
        verified: "github.com/namnh198/lodev/",
        using: :homebrew_curl,
        cookies: {
          "license" => "accept-backup",
        }
    end
  end

  name "lodev"
  desc "LODEV - Local Development Environment for Docker"
  homepage "https://github.com/namnh198/lodev"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "mkcert",
    ]

  binary "lodev"
  bash_completion "completions/lodev_bash_completions.bash"
  fish_completion "completions/lodev_fish_completions.fish"
  zsh_completion "completions/lodev_zsh_completions.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/lodev"]
    end
  end

  # No zap stanza required

end
